version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hospital-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mail-dev:
    container_name: mail-dev-bs
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - hospital-app

  backend:
    container_name: hospital-services
    build: ./hospital-services
    env_file: .env
    ports:
      - "8090:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - hospital-app
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  frontend:
    container_name: hospital-ui
    build: ./hospital-ui
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - hospital-app

networks:
  hospital-app:
    driver: bridge

volumes:
  mysql-data: